// custom.d.ts
// This file is automatically generated.
// It is not recommended to edit this file manually.
declare module '*.js';
declare module 'js-base64';
declare module '*.jsx';
declare module '@kube-design/components';
declare module 'components/Base';
declare module 'stores/*';
declare module 'components/*';
declare module '*.scss';
declare module 'utils';
declare module 'utils/*';
declare module 'lodash';
declare module 'mobx';
declare module '*.tsx';
declare module 'assets';
declare module 'react-router-dom'
declare module 'clusters/*';
declare module 'projects/*';
declare module 'apps/*';
declare module 'workspaces/*';
declare module 'core/*';
declare module '*.svg' {
  import React = require('react');
  export const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  const src: string;
  export default src;
}
